package clipboard

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"strings"
	"sync"
	"time"
	"unicode"
	"unicode/utf8"
)

// ── 内容类型（kind）─────────────────────────────────────────────

// 与 DESIGN.md §4.1 的 items.kind 取值一致。
const (
	KindText  = "text"
	KindHTML  = "html"
	KindRTF   = "rtf"
	KindImage = "image"
	KindFiles = "files"
	KindMixed = "mixed"
)

// PreviewMaxChars 是列表摘要的截断长度（DESIGN.md §4.1：preview 截断 200 字符）。
const PreviewMaxChars = 200

// TextMaxCharsDefault 对应设置项 capture.textMaxChars 的默认值（保留前 256K 字符）。
const TextMaxCharsDefault = 262144

// ── 原始类型名 → 角色归并 ────────────────────────────────────────
//
// macOS 给的是 UTI（public.utf8-plain-text …），Windows 给的是格式名或
// CF_* 常量名。归并到同一组 Role 之后，filter 与 normalize 就能完全平台无关。
//
// Windows 侧的约定：保密标记类格式只有在其值"确实触发排除"时才写进
// Raw.RawTypes（见 windows.go），因此这里的判定可以退化为纯名字查表。

// Role 是一个剪贴板表示在语义上的类别。
type Role string

const (
	RoleText    Role = "text"
	RoleHTML    Role = "html"
	RoleRTF     Role = "rtf"
	RoleImage   Role = "image"
	RoleFiles   Role = "files"
	RolePrivate Role = "private"
	RoleUnknown Role = "unknown"
)

// rawTypeRoles 是类型名（统一小写）到角色的查表。
var rawTypeRoles = map[string]Role{
	// ── macOS / UTI ──
	"public.utf8-plain-text":           RoleText,
	"public.utf16-plain-text":          RoleText,
	"public.utf16-external-plain-text": RoleText,
	"public.text":                      RoleText,
	"nsstringpboardtype":               RoleText,
	"public.html":                      RoleHTML,
	"apple html pasteboard type":       RoleHTML,
	"public.rtf":                       RoleRTF,
	"public.rtfd":                      RoleRTF,
	"com.apple.flat-rtfd":              RoleRTF,
	"public.tiff":                      RoleImage,
	"public.png":                       RoleImage,
	"public.jpeg":                      RoleImage,
	"public.heic":                      RoleImage,
	"com.compuserve.gif":               RoleImage,
	"public.file-url":                  RoleFiles,
	"nsfilenamespboardtype":            RoleFiles,

	// ── Windows ──
	"cf_unicodetext":     RoleText,
	"cf_text":            RoleText,
	"cf_oemtext":         RoleText,
	"html format":        RoleHTML,
	"rich text format":   RoleRTF,
	"cf_dibv5":           RoleImage,
	"cf_dib":             RoleImage,
	"cf_bitmap":          RoleImage,
	"png":                RoleImage,
	"cf_hdrop":           RoleFiles,
	"filenamew":          RoleFiles,
	"filename":           RoleFiles,
	"preferred dropfile": RoleFiles,

	// ── 保密标记 ──
	"org.nspasteboard.concealedtype":               RolePrivate,
	"org.nspasteboard.transienttype":               RolePrivate,
	"org.nspasteboard.autogeneratedtype":           RolePrivate,
	"com.agilebits.onepassword":                    RolePrivate,
	"clipboard viewer ignore":                      RolePrivate,
	"excludeclipboardcontentfrommonitorprocessing": RolePrivate,
	"canincludeinclipboardhistory":                 RolePrivate,
	"canuploadtocloudclipboard":                    RolePrivate,
	"cf_clipboardviewerignore":                     RolePrivate,
}

// ClassifyRawType 把平台原始类型名归并成 Role。未知类型返回 RoleUnknown。
func ClassifyRawType(name string) Role {
	if r, ok := rawTypeRoles[strings.ToLower(strings.TrimSpace(name))]; ok {
		return r
	}
	return RoleUnknown
}

// IsPrivateTypeNames 判断一组原始类型名里有没有"请勿记录"标记。
func IsPrivateTypeNames(names []string) bool {
	for _, n := range names {
		if ClassifyRawType(n) == RolePrivate {
			return true
		}
	}
	return false
}

// HasRole 判断一组原始类型名里有没有指定角色。
func HasRole(names []string, role Role) bool {
	for _, n := range names {
		if ClassifyRawType(n) == role {
			return true
		}
	}
	return false
}

// ── Content：用于指纹与摘要的规范内容视图 ────────────────────────

// Content 是一次剪贴板内容的规范表示。指纹、摘要、落库都从它派生，
// 这样 Raw（采集入口）与 Payload（回写入口）不会各算一套。
type Content struct {
	Text  *string
	HTML  *string
	RTF   []byte
	PNG   []byte
	Files []string
}

// Content 从采集快照派生规范内容。
func (r *Raw) Content() Content {
	if r == nil {
		return Content{}
	}
	c := Content{Text: r.Text, HTML: r.HTML, RTF: r.RTF, Files: r.Files}
	if r.Image != nil {
		c.PNG = r.Image.PNG
	}
	return c
}

// Content 从回写载荷派生规范内容。
//
// 必须与 (*Raw).Content 逐字节一致：SelfWriteGuard 靠两条路径算出的同一指纹
// 判定"这是我们自己写的"，任何不一致都会导致自捕获。见 normalize_test.go
// 的 TestContentRoundTripFingerprintMatches。
func (p *Payload) Content() Content {
	if p == nil {
		return Content{}
	}
	return Content{Text: p.Text, HTML: p.HTML, RTF: p.RTF, PNG: p.PNG, Files: p.Files}
}

// Empty 判断是否没有任何内容。
func (c Content) Empty() bool {
	return c.Text == nil && c.HTML == nil &&
		len(c.RTF) == 0 && len(c.PNG) == 0 && len(c.Files) == 0
}

// 表示组：capture.types 的取值域。它比 items.kind 粗一档。
//
// 之所以要这一层：文本类剪贴板数据从来不是"一个" flavor —— 从浏览器复制
// 一定同时带 text + html，从 Word 复制还带 rtf。它们语义上是同一份内容的
// 三种繁简写法，归到同一组才不会让"混合"泛滥。
const (
	GroupText  = "text"
	GroupImage = "image"
	GroupFiles = "files"
)

// Groups 返回内容包含的表示组，按固定顺序（text → image → files）。
func (c Content) Groups() []string {
	textish := (c.Text != nil && *c.Text != "") ||
		(c.HTML != nil && *c.HTML != "") ||
		len(c.RTF) > 0
	out := make([]string, 0, 3)
	if textish {
		out = append(out, GroupText)
	}
	if len(c.PNG) > 0 {
		out = append(out, GroupImage)
	}
	if len(c.Files) > 0 {
		out = append(out, GroupFiles)
	}
	return out
}

// Kind 归并出 items.kind（DESIGN.md §4.1 取值）。
//
// 文本组内按"信息量"取最高的那个：html > rtf > text。HTML 剪贴板数据天然
// 附带一份纯文本孪生体，若把这种情形判成 mixed，几乎每个网页复制都会是
// mixed，取值就没有意义了。文本组 + 图片（或文件）这种真正的多形态才是 mixed。
func (c Content) Kind() string {
	hasText := c.Text != nil && *c.Text != ""
	hasHTML := c.HTML != nil && *c.HTML != ""
	hasRTF := len(c.RTF) > 0
	hasImg := len(c.PNG) > 0
	hasFiles := len(c.Files) > 0

	textKind := ""
	switch {
	case hasHTML:
		textKind = KindHTML
	case hasRTF:
		textKind = KindRTF
	case hasText:
		textKind = KindText
	}

	groups := 0
	if textKind != "" {
		groups++
	}
	if hasImg {
		groups++
	}
	if hasFiles {
		groups++
	}

	switch groups {
	case 0:
		return ""
	case 1:
		switch {
		case textKind != "":
			return textKind
		case hasImg:
			return KindImage
		default:
			return KindFiles
		}
	default:
		return KindMixed
	}
}

// Fingerprint 对**完整内容**做 sha256（DESIGN.md §14 第 16 条：超大文本
// 截断存储但要保留完整指纹，否则去重会漏）。
//
// 编码方式：按固定顺序遍历各表示，每段用 <role 长度><role><内容长度><内容>
// 的长度前缀分帧。长度前缀保证 "ab"+"c" 与 "a"+"bc" 不会撞哈希。
func Fingerprint(c Content) string {
	h := sha256.New()
	var buf [binary.MaxVarintLen64]byte
	writePart := func(role string, b []byte) {
		n := binary.PutUvarint(buf[:], uint64(len(role)))
		h.Write(buf[:n])
		h.Write([]byte(role))
		n = binary.PutUvarint(buf[:], uint64(len(b)))
		h.Write(buf[:n])
		h.Write(b)
	}

	if c.Text != nil {
		writePart("text", []byte(*c.Text))
	}
	if c.HTML != nil {
		writePart("html", []byte(*c.HTML))
	}
	if len(c.RTF) > 0 {
		writePart("rtf", c.RTF)
	}
	if len(c.PNG) > 0 {
		writePart("image", c.PNG)
	}
	if len(c.Files) > 0 {
		writePart("files", []byte(strings.Join(c.Files, "\x00")))
	}
	return "sha256:" + hex.EncodeToString(h.Sum(nil))
}

// Fingerprint 采集侧入口。与 (*Payload).Fingerprint 必须等价。
func (r *Raw) Fingerprint() string { return Fingerprint(r.Content()) }

// Fingerprint 回写侧入口。与 (*Raw).Fingerprint 必须等价。
func (p *Payload) Fingerprint() string { return Fingerprint(p.Content()) }

// ── 截断与摘要 ──────────────────────────────────────────────────

// TruncateText 按**字符**（而非字节）截断，避免切断 UTF-8 序列。
// 返回截断后的字符串与是否发生了截断。
func TruncateText(s string, maxChars int) (string, bool) {
	if maxChars <= 0 || utf8.RuneCountInString(s) <= maxChars {
		return s, false
	}
	n := 0
	for i := range s {
		if n == maxChars {
			return s[:i], true
		}
		n++
	}
	return s, false
}

// collapseSpace 把连续空白折叠成单个空格，并去掉首尾空白。
// 摘要是单行展示，换行会让列表高度抖动。
func collapseSpace(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	space := false
	for _, r := range s {
		if unicode.IsSpace(r) {
			space = true
			continue
		}
		if space && b.Len() > 0 {
			b.WriteByte(' ')
		}
		space = false
		b.WriteRune(r)
	}
	return b.String()
}

// stripHTMLTags 做一版极简的 HTML 取文本：去标签、解几个常见实体。
// 目标只是列表摘要，不追求正确解析（真正的解析等 M2 前端做富文本预览）。
func stripHTMLTags(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	depth := 0
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '<':
			depth++
			// 把 <br> / <p> 这类块级标签折算成一个空格，避免粘连
			if strings.HasPrefix(s[i:], "<br") || strings.HasPrefix(s[i:], "<p") ||
				strings.HasPrefix(s[i:], "</p") || strings.HasPrefix(s[i:], "<div") ||
				strings.HasPrefix(s[i:], "<li") {
				b.WriteByte(' ')
			}
		case '>':
			if depth > 0 {
				depth--
			}
		default:
			if depth == 0 {
				b.WriteByte(s[i])
			}
		}
	}
	out := b.String()
	repl := strings.NewReplacer(
		"&nbsp;", " ", "&lt;", "<", "&gt;", ">",
		"&quot;", `"`, "&#39;", "'", "&amp;", "&",
	)
	return repl.Replace(out)
}

// stripRTF 做一版极简的 RTF 取文本：去掉 \word 控制字、{\*\...} 组与花括号。
func stripRTF(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '\\':
			// 跳过控制字或转义字符
			i++
			if i >= len(s) {
				break
			}
			if s[i] == '\'' || !isAlphaByte(s[i]) {
				// \'hh 十六进制转义：忽略（非 ASCII 文本走 \uNNNN）
				if s[i] == '\'' {
					i += 2
				} else if s[i] == '\\' || s[i] == '{' || s[i] == '}' {
					b.WriteByte(s[i])
				}
				continue
			}
			// 控制字：跳过字母，再跳过可选数字与一个空格
			for i < len(s) && isAlphaByte(s[i]) {
				i++
			}
			if i < len(s) && s[i] == '-' {
				i++
			}
			for i < len(s) && s[i] >= '0' && s[i] <= '9' {
				i++
			}
			if i < len(s) && s[i] == ' ' {
				// 控制字后的单个空格是分隔符，不产出
			} else {
				i--
			}
		case '{', '}':
			// 分组符不产出
		default:
			b.WriteByte(s[i])
		}
	}
	return b.String()
}

func isAlphaByte(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
}

// Preview 生成列表摘要（DESIGN.md §4.1：截断 200 字符）。
//
// imageW / imageH 仅对图片有意义，传 0 时退化为 "图片"。
func Preview(c Content, kind string, imageW, imageH int) string {
	var raw string
	switch kind {
	case KindImage:
		if imageW > 0 && imageH > 0 {
			return truncateRunes("图片 "+itoa(imageW)+" × "+itoa(imageH), PreviewMaxChars)
		}
		return "图片"
	case KindFiles:
		n := len(c.Files)
		if n == 0 {
			return "文件"
		}
		base := lastPathComponent(c.Files[0])
		if n > 1 {
			return truncateRunes(base+" 等 "+itoa(n)+" 个文件", PreviewMaxChars)
		}
		return truncateRunes(base, PreviewMaxChars)
	case KindRTF:
		if len(c.RTF) > 0 {
			raw = stripRTF(string(c.RTF))
			break
		}
	}
	if raw == "" {
		switch {
		case c.Text != nil && *c.Text != "":
			raw = *c.Text
		case c.HTML != nil && *c.HTML != "":
			raw = stripHTMLTags(*c.HTML)
		case len(c.RTF) > 0:
			raw = stripRTF(string(c.RTF))
		}
	}
	// mixed：HTML 的标签会污染摘要，优先取纯文本；没有纯文本再剥标签
	if kind == KindMixed && c.Text != nil && *c.Text != "" {
		raw = *c.Text
	}
	return truncateRunes(collapseSpace(raw), PreviewMaxChars)
}

func truncateRunes(s string, max int) string {
	out, _ := TruncateText(s, max)
	return out
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}

func lastPathComponent(p string) string {
	if i := strings.LastIndexAny(p, `/\`); i >= 0 && i+1 < len(p) {
		return p[i+1:]
	}
	return p
}

// ── 去抖 ────────────────────────────────────────────────────────

// Debouncer 合并连续的剪贴板变更：同一指纹在窗口内的重复事件被丢弃
// （DESIGN.md §2「去抖设计」，默认 120ms）。
//
// 只记"最近一次指纹与时刻"，不维护 map——单次复制的重复写入都是紧挨着的，
// 常量内存即可覆盖真实场景，也避免热路径上的 map 分配。
type Debouncer struct {
	mu     sync.Mutex
	lastFP string
	lastAt time.Time
	window time.Duration
}

// NewDebouncer 创建去抖器。window <= 0 表示关闭去抖。
func NewDebouncer(window time.Duration) *Debouncer {
	return &Debouncer{window: window}
}

// ShouldProcess 返回 false 表示该指纹在窗口内刚处理过，应丢弃。
func (d *Debouncer) ShouldProcess(fp string, now time.Time) bool {
	if d == nil || d.window <= 0 {
		return true
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	if d.lastFP == fp && now.Sub(d.lastAt) < d.window {
		d.lastAt = now
		return false
	}
	d.lastFP = fp
	d.lastAt = now
	return true
}

// Reset 清空去抖状态（例如暂停记录后重新开始）。
func (d *Debouncer) Reset() {
	if d == nil {
		return
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	d.lastFP = ""
	d.lastAt = time.Time{}
}
