// Command genpinyin 生成 pinyin/table.go。
//
// 为什么把生成器也入库：这张表是**外部数据**（汉字→拼音首字母），
// 直接手写或从别处拷一份进仓库都不可复核。留一个可重跑的生成器，
// 任何人（包括未来的我）都能验证"表里的值确实来自那个数据源"。
//
// 用法：
//
//	go run ./tools/genpinyin                 # 从内置 URL 下载并重新生成
//	go run ./tools/genpinyin -src pinyin.txt # 用本地已下载的源文件
//
// 数据源：https://github.com/mozillazg/pinyin-data 的 pinyin.txt（MIT）。
// 该文件每行形如：
//
//	U+4E00: yī  # 一
//	U+4E0A: shàng,shang  # 上
//
// 我们只保留**第一个读音的首字母**：多音字取最常用的那个，这是取舍不是
// bug —— 拼音搜索是"想起来大概怎么念"的模糊入口，不是注音工具。
package main

import (
	"bufio"
	"encoding/base64"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"
)

const (
	// sourceURL 是上游原始数据。
	sourceURL = "https://raw.githubusercontent.com/mozillazg/pinyin-data/master/pinyin.txt"

	// lo / hi 是收录范围：CJK 统一表意文字基本区。
	// 不往扩展区（U+3400 起、U+20000 起）扩：那些是生僻字与异体字，
	// 代价是表体积翻几倍，收益接近于零。
	lo = 0x4E00
	hi = 0x9FFF

	outPath = "pinyin/table.go"
)

// 读第一行形如 `U+4E00: yī,...` 的记录，取第一个读音的首字母。
var lineRE = regexp.MustCompile(`^U\+([0-9A-Fa-f]+):\s*([a-zA-Z]+)`)

func main() {
	src := flag.String("src", "", "本地源文件路径；为空则从网络下载")
	out := flag.String("out", outPath, "输出文件路径")
	flag.Parse()

	f, err := openSource(*src)
	if err != nil {
		log.Fatalf("读取数据源失败：%v", err)
	}
	defer func() { _ = f.Close() }()

	n := hi - lo + 1
	// 0 表示"这个码位没有拼音信息"。用 0 而不是 '?' 是为了在生成侧就能
	// 区分"未知"与"真的以某个字母开头"。
	tbl := make([]byte, n)

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<20)
	known := 0
	for sc.Scan() {
		m := lineRE.FindStringSubmatch(strings.TrimSpace(sc.Text()))
		if m == nil {
			continue
		}
		cp64, err := strconv.ParseInt(m[1], 16, 32)
		if err != nil {
			continue
		}
		cp := int(cp64)
		if cp < lo || cp > hi {
			continue
		}
		b := m[2][0] | 0x20 // 统一小写
		if b < 'a' || b > 'z' {
			continue
		}
		tbl[cp-lo] = b
		known++
	}
	if err := sc.Err(); err != nil {
		log.Fatalf("扫描数据源失败：%v", err)
	}
	if known < 15000 {
		// 防"上游改了格式、我们静默生成了半张表"。
		// 基本区有 2 万多个码位，正常应命中 2 万上下；低于 1.5 万说明
		// 解析规则已经对不上了，必须停下来看，而不是写一份坏表进仓库。
		log.Fatalf("只解析出 %d 个汉字，远低于预期——上游格式可能变了，请检查解析规则", known)
	}

	// base64 而不是十六进制数组：字节值全是可打印的 a-z 加少量 0，
	// base64 的源码体积（约 28 KB）与可读性都优于带转义的字符串字面量
	// （\x00 转义会让单行长度失控），且解码只在 init 里做一次。
	enc := base64.StdEncoding.EncodeToString(tbl)

	header := fmt.Sprintf(`// Code generated by tools/genpinyin. DO NOT EDIT.
//
// 汉字 → 拼音首字母表，覆盖 %#x..%#x（CJK 基本区，共 %d 个码位）。
//
// 数据源：%s
// 记录时间：%s
// 本表共收录 %d 个有拼音信息的码位；其余为 0，表示未知。
//
// 编码：base64 → 原始字节序列，第 i 个字节对应码位 lo+i，
// 值为该字拼音首字母的小写 ASCII，0 表示未知。
//
// 用 base64 而不是转义字符串或十六进制数组的原因：字节分布是"几乎是
// 清一色的小写字母 + 少量 0"，base64 的源码体积（约 %d KB）与可读性都最好，
// 解码只在 init() 里做一次，代价是一次 %d 字节的分配。
package pinyin

import "encoding/base64"

const (
	// tableLo / tableHi 是这张表覆盖的码位闭区间。
	tableLo = %#x
	tableHi = %#x
)

// tableB64 是压缩后的表体（见文件头说明）。
const tableB64 = "%s"

// table 在 init 时解码一次。之后所有查询都是对它的下标访问。
var table = mustDecodeTable()

func mustDecodeTable() []byte {
	b, err := base64.StdEncoding.DecodeString(tableB64)
	if err != nil {
		// 常量表解不开只可能是源码被改坏了。常量字符串的长度/内容校验
		// 只能在运行期做，所以这里 panic —— 它发生在进程启动的第一毫秒，
		// 不可能被用户当成"正常行为"。
		panic("pinyin: 内置表损坏：" + err.Error())
	}
	if len(b) != tableHi-tableLo+1 {
		panic("pinyin: 内置表长度与码位范围不符")
	}
	return b
}
`, lo, hi, n, sourceURL, time.Now().Format("2006-01-02"), known, len(enc)/1024, n, lo, hi, enc)

	formatted, err := format.Source([]byte(header))
	if err != nil {
		// 格式化失败时把原文写出去，方便人工看是哪一行的问题。
		_ = os.WriteFile(*out+".raw", []byte(header), 0o644)
		log.Fatalf("gofmt 失败（原文已写到 %s.raw）：%v", *out, err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		log.Fatalf("写入 %s 失败：%v", *out, err)
	}
	log.Printf("已生成 %s：%d 个码位，%d 个有拼音，源码 %d 字节", *out, n, known, len(formatted))
}

func openSource(local string) (io.ReadCloser, error) {
	if local != "" {
		return os.Open(local)
	}
	c := &http.Client{Timeout: 60 * time.Second}
	resp, err := c.Get(sourceURL)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		_ = resp.Body.Close()
		return nil, fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	return resp.Body, nil
}
