// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accessory():Promise<boolean>;

export function ModeName():Promise<string>;

export function ProbeLog():Promise<Array<string>>;

export function ProbeState():Promise<Record<string, boolean>>;
