// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accessory() {
  return window['go']['main']['App']['Accessory']();
}

export function ModeName() {
  return window['go']['main']['App']['ModeName']();
}

export function ProbeLog() {
  return window['go']['main']['App']['ProbeLog']();
}

export function ProbeState() {
  return window['go']['main']['App']['ProbeState']();
}
